24/05/06 :: 0.5
dbcp2에서 dbcp로 downgrade :: 둘의 class 구조가 다르다고 한다.

java.io.FileNotFoundException: class path resource
[org/apache/commons/dbcp/BasicDataSource.class] cannot be opened because
it does not exist

찾는 file은 dbcp이기에 downgrade가 맞다고 판단했다.