24/05/06 :: 0.7
dbcp 삭제 후 배포했더니, 다시 dbcp 없다는 오류가 난다.

java.io.FileNotFoundException: class path resource
[org/apache/commons/dbcp/BasicDataSource.class] cannot be opened because
it does not exist

그러면 추가한 dbcp의 문제가 아닌 것인가? 정말 나머지 전체 third party library를 하나씩 검사해봐야 하는가?